- name: Install Apache on webserver
  yum:
    name: httpd
    state: present 

- name: create document roots
  file:
    path: "{{ item.document_root }}"
    state: directory
  loop: "{{ virtualhosts }}"

- name: Create virtual hosts configuration files
  template:
    src: httpd.conf.j2
    dest: "/etc/httpd/conf.d/{{ item.port }}.conf"
  loop: "{{ virtualhosts }}"

- name: add vhost ports to httpd conf file 
  lineinfile:
    path: "/etc/httpd/conf.d/vhosts.conf"
    insertafter: '^Listen'
    line: "{{ item }}"
    create: yes 
  loop:
    - Listen 5000
    - Listen 6000
    - Listen 7000
    
- name: Copy HTML files to document roots
  copy:
    src: "{{ item.html_file }}"
    dest: "{{ item.document_root  }}/index.html"
  loop: "{{ virtualhosts }}"
  notify: restart Apache

- name: Set permissions for vhosts document_roots
  file:
    path: "{{ item.document_root }}" 
    owner: apache
    group: apache
    mode: '0755'
    recurse: yes
  loop: "{{ virtualhosts }}"

- name: Allow traffic on port 80
  firewalld:
    port: "{{ item.port }}/tcp"
    permanent: yes
    state: enabled
    immediate: yes
  loop: "{{ virtualhosts }}"

- name: Ensure SELinux is disabled in the config file
  replace:
    path: /etc/selinux/config
    regexp: '^SELINUX=.*'
    replace: 'SELINUX=disabled'


# - name: Install Git
#   yum:
#     name: git
#     state: present

# # - name: Clone the repository
# #   git:
# #     repo: "{{ git_repo }}"
# #     dest: "{{ web_app_dir }}"
# #     version: master
# #     force: yes
# #     update: yes
