---
- name: Insert data into MariaDB database
  hosts: databases
  become: yes
  vars:
    db_name: Code_Killers
    db_table: students
    db_user: root
    db_password: password
   
  tasks:

    - name: Ensure the database is created
      ansible.builtin.mysql_db:
        name: "Code_Killers"
        state: present
        login_user: root
        login_password: "password"

    - name: Create a table in the database
      mysql_query:
        login_user: root
        login_password: "password"
        login_db: "{{ db_name }}"
        query: |
          CREATE TABLE IF NOT EXISTS {{ db_table }} (
            name VARCHAR(255) NOT NULL,
            state VARCHAR(255) UNIQUE NOT NULL
          );
          
    - name: Insert values into the table ignoring duplicates
      community.mysql.mysql_query:
        login_user: root
        login_password: "password"
        login_db: "{{ db_name }}"
        query: |
          INSERT IGNORE INTO students (name, state) VALUES
          ('Ferdows', 'Virginia!'),
          ('Eric', 'Virginia.'),
          ('Abrar', 'Virginia'),
          ('Sameem', 'virginia?'),
          ('Iryna', 'Illinois'),
          ('Dilnoza', 'Florida'),
          ('Fariza', 'Pensylvania');
