---
- name: Configure servers
  hosts: all
  become: yes
  tasks:
    - name: Disable root SSH login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
      notify: Restart SSH

    - name: Ensure firewall is enabled
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Disable SELinux
      selinux:
        state: disabled

    - name: Set password for all users to 'password'
      user:
        name: "{{ item }}"
        password: "{{ 'password' | password_hash('sha256') }}"
      loop: "{{ ansible_facts.get('passwd', ['ansible', 'root']) }}"
      when: ansible_facts.get('passwd', ['ansible', 'root']) is defined

  handlers:
    - name: Restart SSH
      service:
        name: sshd
        state: restarted