---
- hosts: nagios_server
  become: yes
  tasks:
    - name: Install Nagios and required packages
      yum:
        name:
          - httpd
          - nagios
          - nagios-plugins-all
          - nagios-plugins-nrpe
          - nrpe
          - epel-release
        state: present

    - name: Enable and start Nagios and Apache services
      systemd:
        name: "{{ item }}"
        enabled: yes
        state: started
      loop:
        - nagios
        - httpd

    - name: Configure Nagios to monitor the servers
      template:
        src: nagios.cfg.j2
        dest: /usr/local/nagios/etc/nagios.cfg
      notify:
        - Restart Nagios

    - name: Configure Nagios contacts
      template:
        src: contacts.cfg.j2
        dest: /usr/local/nagios/etc/objects/contacts.cfg
      notify:
        - Restart Nagios

    - name: Configure Nagios host groups
      template:
        src: hostgroups.cfg.j2
        dest: /usr/local/nagios/etc/objects/hostgroups.cfg
      notify:
        - Restart Nagios

    - name: Create configuration for each server
      template:
        src: host.cfg.j2
        dest: /usr/local/nagios/etc/servers/{{ item }}.cfg
      loop:
        - prdx-db101.ziyotek1.local
        - prdx-webserver101.ziyotek1.local
        - prdx-webserver102.ziyotek1.local
        - prdx-webserver103.ziyotek1.local
        - prdx-haproxy101.ziyotek1.local
        - prdx-nagios101.ziyotek1.local
        - prdx-dprimary101.ziyotek1.local
        - prdx-dworker101.ziyotek1.local
        - prdx-dworker102.ziyotek1.local
        - prdx-kube101.ziyotek1.local
        - prdx-dns101.ziyotek1.local
        - prdx-jenkins101.ziyotek1.local
      notify:
        - Restart Nagios

  handlers:
    - name: Restart Nagios
      systemd:
        name: nagios
        state: restarted

- hosts: all_servers
  become: yes
  tasks:
    - name: Install NRPE and Nagios plugins
      yum:
        name:
          - nagios-plugins-all
          - nagios-plugins-nrpe
          - nrpe
        state: present

    - name: Configure NRPE to allow Nagios server
      lineinfile:
        path: /etc/nagios/nrpe.cfg
        regexp: '^allowed_hosts='
        line: 'allowed_hosts={{ 192.168.154.15 }}'

    - name: Configure monitoring checks
      copy:
        src: /etc/nagios/nrpe_local.cfg
        dest: /etc/nagios/nrpe.d/custom.cfg
        mode: '0644'

    - name: Start and enable NRPE service
      systemd:
        name: nrpe
        enabled: yes
        state: started  
